// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "warehouse_project/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// PositionRepo is an autogenerated mock type for the positionRepo type
type PositionRepo struct {
	mock.Mock
}

type PositionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PositionRepo) EXPECT() *PositionRepo_Expecter {
	return &PositionRepo_Expecter{mock: &_m.Mock}
}

// FindAllByIDs provides a mock function with given fields: id
func (_m *PositionRepo) FindAllByIDs(id []int64) ([]*model.Position, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByIDs")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func([]int64) ([]*model.Position, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func([]int64) []*model.Position); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PositionRepo_FindAllByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByIDs'
type PositionRepo_FindAllByIDs_Call struct {
	*mock.Call
}

// FindAllByIDs is a helper method to define mock.On call
//   - id []int64
func (_e *PositionRepo_Expecter) FindAllByIDs(id interface{}) *PositionRepo_FindAllByIDs_Call {
	return &PositionRepo_FindAllByIDs_Call{Call: _e.mock.On("FindAllByIDs", id)}
}

func (_c *PositionRepo_FindAllByIDs_Call) Run(run func(id []int64)) *PositionRepo_FindAllByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int64))
	})
	return _c
}

func (_c *PositionRepo_FindAllByIDs_Call) Return(_a0 []*model.Position, _a1 error) *PositionRepo_FindAllByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PositionRepo_FindAllByIDs_Call) RunAndReturn(run func([]int64) ([]*model.Position, error)) *PositionRepo_FindAllByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewPositionRepo creates a new instance of PositionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionRepo {
	mock := &PositionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
