// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "warehouse_project/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// ClientRepo is an autogenerated mock type for the clientRepo type
type ClientRepo struct {
	mock.Mock
}

type ClientRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRepo) EXPECT() *ClientRepo_Expecter {
	return &ClientRepo_Expecter{mock: &_m.Mock}
}

// CreateClient provides a mock function with given fields: client
func (_m *ClientRepo) CreateClient(client *model.Client) (*model.Client, error) {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 *model.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Client) (*model.Client, error)); ok {
		return rf(client)
	}
	if rf, ok := ret.Get(0).(func(*model.Client) *model.Client); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRepo_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type ClientRepo_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - client *model.Client
func (_e *ClientRepo_Expecter) CreateClient(client interface{}) *ClientRepo_CreateClient_Call {
	return &ClientRepo_CreateClient_Call{Call: _e.mock.On("CreateClient", client)}
}

func (_c *ClientRepo_CreateClient_Call) Run(run func(client *model.Client)) *ClientRepo_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Client))
	})
	return _c
}

func (_c *ClientRepo_CreateClient_Call) Return(_a0 *model.Client, _a1 error) *ClientRepo_CreateClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientRepo_CreateClient_Call) RunAndReturn(run func(*model.Client) (*model.Client, error)) *ClientRepo_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientRepo creates a new instance of ClientRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientRepo {
	mock := &ClientRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
